<!DOCTYPE html>
<html lang="en">
<head>
    <title>Places - Assignment06 PHP FWD Web Scripting 2</title>  
    
    <link rel="apple-touch-icon" sizes="180x180" href="favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="favicon/favicon-16x16.png">
        
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <meta name="description" content="BCIT FWD Web Scripting 2: Using PHP and MySQL to develop server side solutions for web development.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    <meta charset="UTF-8">    
    

	<!-- stylesheets related to the jQuery lightbox -->		
	<link rel="stylesheet" href="css/lightbox.css">
    <link rel="stylesheet" href="css/styles.css">    

	<!-- load the jQuery and lightbox scripts... -->
	<script src="js/jquery-1.11.0.min.js" defer></script>
	<script src="js/lightbox.js" defer></script>

</head>
<body>
<div id="wrapper">
    <header>
        <h1>Places - Assignment06</h1>
    </header>

	<nav>		
		<ul>
            <li><a href="index.php">Home</a></li>                        
			<li><a href="kittens.php">Kittens</a></li>            
			<li><a href="landscapes.php">Landscapes</a></li>     
			<li><a href="places.php">Places</a></li>     
		</ul>
	</nav>
    <main>             
    <section>


    
<!-- 
following is a hard-coded example of the output
PHP will need to generate dynamically.

to complete this assignment, 
dont use any hard coded HTML like what you see below.
replace these hard coded examples with dynamic PHP output

be sure PHP displays a lightox thumbnail 
for each image in the folder

you need to replace the hard coded HTML below with PHP output
be careful to ensure all the attributes and thier alues will be 
included correctly in the resulting response sent to the client
-->

<?php

include("functions.php");
displayGallery('/places');

?>
<!-- the lightbox gallery unordered list above should be generated by PHP -->	

    </section>        
    </main>
    <footer>
        <p>Copyleft 20** <span>&copy;</span> - PHP FWD Web Scripting 2</p>
    </footer>
</div>    
</body>
</html>